### ISSUE TITLE
Missing py.typed file

### ISSUE THREAD

**Issue by bh2smith** [pinnaculum/py-multiformats-cid#4]
https://github.com/pinnaculum/py-multiformats-cid/blob/333a516be386442c2f6388e65749e4ab714f89bb/setup.cfg#L39

Unfortunately, this file is still not being included in the published package. I think it needs to be changed to the root directory:

```
multiformats_cid = py.typed
```

**Comment by PancakesArchitect** [comment]
This is, as the setuptools doc seem to indicate, the right way to do it though (the config keys in *options.package_data* should be python package names). edit: *seems to work*

**Comment by bh2smith** [comment]
Excited to start using it typed!

**Comment by PancakesArchitect** [comment]
Publishing it now.  CI won't test python 3.7 now (gotta save energy).

**Comment by bh2smith** [comment]
Might as well consider 3.7 a dinosaur then!

It's probably because of that PR I had closed with the vertical pipes not being a thing back then.

**Comment by PancakesArchitect** [comment]
> It's probably because of that PR I had closed with the vertical pipes not being a thing back then.

Yeah flake8 was sad.

So i've thought about how to improve the library which right now is really a basic API. In [galacteek](https://github.com/pinnaculum/galacteek) over time i wrote a lot of functions to deal with CIDs, convert CIDs, format them etc ... i think conversion functions, that kind of things could benefit the library, aside other improvements. If you have any ideas, things that you'd like to be included don't hesitate.
